version: '3'

services:
  retrieval:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATASTORE=pinecone
      - BEARER_TOKEN=secret
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - OPENAI_ORGANIZATION=$OPENAI_ORGANIZATION
      - PINECONE_API_KEY=$PINECONE_API_KEY
      - PINECONE_ENVIRONMENT=$PINECONE_ENVIRONMENT
      - PINECONE_INDEX=$PINECONE_INDEX
